### ISSUE TITLE
extract_kraken_reads.py  ValueError: invalid literal for int() with base 10: 'tot_lvl'

### ISSUE THREAD

**Issue by RieLuc23** [jenniferlu717/KrakenTools#100]
When executing extract_kraken_reads.py using a combined report (which was generated by combine_kreports.py) and using one concatenated fasta file I get the following error: 

 extract_kraken_reads.py -k combined.report -s combined.fasta -o outputnew.fasta -t 590 454169 115981 90371 286
PROGRAM START TIME: 09-27-2024 08:03:49
	5 taxonomy IDs to parse
>> STEP 1: PARSING KRAKEN FILE FOR READIDS combined.report
	0 reads processedTraceback (most recent call last):
  File "/teachstor/share/toolsSS24/workspace/Team_LuVi/Lucas/miniconda3/envs/krakentools/bin/extract_kraken_reads.py", line 433, in <module>
    main()
  File "/teachstor/share/toolsSS24/workspace/Team_LuVi/Lucas/miniconda3/envs/krakentools/bin/extract_kraken_reads.py", line 285, in main
    [tax_id, read_id] = process_kraken_output(line)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/teachstor/share/toolsSS24/workspace/Team_LuVi/Lucas/miniconda3/envs/krakentools/bin/extract_kraken_reads.py", line 98, in process_kraken_output
    tax_id = int(tax_id)
             ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'tot_lvl'

What could be the problem? 
Thanks

**Comment by RieLuc23** [comment]
the header of the combined.report is: 
```
#Number of Samples: 23
#Total Number of Reads: 256890
```

**Comment by jenniferlu717** [comment]
Oh I see the issue. The output for the combined report isnt formatted to be used in extract_kraken_reads. I'll see if I can fix it
