### ISSUE TITLE
KeyError: 'unclassified (taxid 0)'

### ISSUE THREAD

**Issue by liaochen1988** [jenniferlu717/KrakenTools#21]
When I run make_kreport.py, it generates the following error (KeyError: 'unclassified (taxid 0)'). Does anyone know what causes it?

PROGRAM START TIME: 09-05-2020 13:40:52
>> STEP 1/4: Reading taxonomy kraken2_standard_09042020/mydb_taxonomy.txt...
	722 nodes saved
>> STEP 2/4: Reading kraken file 2105F.kraken2.output.txt...
	36.872 million reads processed
>> STEP 3/4: Creating final tree...
Traceback (most recent call last):
  File "/opt/anaconda3/envs/kraken2/bin/make_kreport.py", line 198, in <module>
    main()
  File "/opt/anaconda3/envs/kraken2/bin/make_kreport.py", line 145, in main
    p_node = taxid2node[curr_tid].parent
KeyError: 'unclassified (taxid 0)'

**Comment by jenniferlu717** [comment]
Did you run kraken with --use-names? The script wasn't built for the output including those. I'll try to add a modification to the script to fix that ASAP but it won't be available for a few days

**Comment by Minamehr** [comment]
Hi, I am getting the same error when I run make_kreport.py, Would you please let me know how I can fix this.

PROGRAM START TIME: 11-16-2021 11:37:32
>> STEP 1/4: Reading taxonomy MY_KRAKEN2_DB/mydb_taxonomy.txt...
	34669 nodes saved
>> STEP 2/4: Reading kraken file S1.krak2...
	0.105 million reads processed
>> STEP 3/4: Creating final tree...
Traceback (most recent call last):
  File "/data/reference/Metawrap/make_kreport.py", line 199, in <module>
    main()
  File "/data/reference/Metawrap/make_kreport.py", line 145, in main
    p_node = taxid2node[curr_tid].parent 
KeyError: 'unclassified (taxid 0)
