### ISSUE TITLE
error in kreport2mpa.py

### ISSUE THREAD

**Issue by Timmywang1** [jenniferlu717/KrakenTools#38]
Hello， 
   Thanks for your powerful tools. I meet a problem,when i run the script:
 /data/Timmy/Bracken/kreport2mpa.py -r ./OUT/TEST.S.bracken -o ./OUT/TEST1.report
##
Traceback (most recent call last):
  File "/data/Timmy/Bracken/kreport2mpa.py", line 173, in <module>
    main()
  File "/data/Timmy/Bracken/kreport2mpa.py", line 128, in main
    report_vals = process_kraken_report(line)
  File "/data/Timmy/Bracken/kreport2mpa.py", line 74, in process_kraken_report
    percents = float(split_str[0])
ValueError: could not convert string to float: Neorhizobium sp. NCHU2750
##
How can i fix it? Thanks for your help.

**Comment by ammaraziz** [comment]
I'm working on this script for a different purpose, so I should be able to assist with this error (but note I'm just a fellow user).

Can you post your TEST.S.bracken? and also the command(s) to generate this as well.

**Comment by jenniferlu717** [comment]
@Timmywang1 What Kraken report file are you using? If you did not generate the default report (--report), the kreport2mpa.py script will not work. 

For example if you used --use-mpa-style, then the kreport2mpa.py file will not work.

**Comment by artur-matysik** [comment]
@Timmywang1 I see that you used the script on bracken output (-o OUTPUT). When running bracken add -w OUTREPORT and use that file instead to feed kreport2mpa.py.

**Comment by laibinhuang** [comment]
I get the same issue and Kraken2 report is not using --use-mpa-style

the ful code:
for i in braken/species/*_report_bracken.txt
do
  filename=$(basename "$i")
  fname="${filename%_report_bracken.txt}"
  python /home/lbhuang/miniconda3/pkgs/krakentools-1.2-pyh5e36f6f_0/python-scripts/kreport2mpa.py -r $i -o braken/species/mpa/${fname}_mpa.txt --display-header
done

the error:
File "/home/lbhuang/miniconda3/pkgs/krakentools-1.2-pyh5e36f6f_0/python-scripts/kreport2mpa.py", line 173, in <module>
    main()
  File "/home/lbhuang/miniconda3/pkgs/krakentools-1.2-pyh5e36f6f_0/python-scripts/kreport2mpa.py", line 128, in main
    report_vals = process_kraken_report(line)
  File "/home/lbhuang/miniconda3/pkgs/krakentools-1.2-pyh5e36f6f_0/python-scripts/kreport2mpa.py", line 74, in process_kraken_report
    percents = float(split_str[0])
ValueError: could not convert string to float: 'Bradyrhizobium sp. CCBAU 051011'

**Comment by leonardo467** [comment]
Any updates about this?

**Comment by mortuseon** [comment]
> @Timmywang1 I see that you used the script on bracken output (-o OUTPUT). When running bracken add -w OUTREPORT and use that file instead to feed kreport2mpa.py.

I am also having this issue when trying to run kreport2mpa on bracken reports, but unfortunately adding -w doesn't help (listed as an illegal option; I don't see it in the documentation either so I assume it is not currently an available parameter). Do you happen to have any ideas as to how to fix this? Thanks so much if so!
