### ISSUE TITLE
error with "combine_mpa.py" script when combining mpa report with header

### ISSUE THREAD

**Issue by weiweiziyan** [jenniferlu717/KrakenTools#52]
Hi,
combine_mpa.py was very useful when I combine the mpa reports without header.

But when I chose to add the header to the mpa report(--display-header), an error was reported (as below). How should I solve it?

Traceback (most recent call last):
  File "combine_mpa.py", line 142, in <module>
    main()
  File "combine_mpa.py", line 83, in main
    [classification, val] = line.strip().split('\t')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jenniferlu717** [comment]
Can you post the header for the mpa report file?

**Comment by weiweiziyan** [comment]
> Can you post the header for the mpa report file?

Thank you！The header is as following
![1](https://user-images.githubusercontent.com/110878053/196312075-075f03cf-16a6-4610-8072-c3ecd0d00b4c.png)
