### ISSUE TITLE
error running kreport2mpa.py script, name 'l_vals' is not defined. 

### ISSUE THREAD

**Issue by Sautumn-Lin** [jenniferlu717/KrakenTools#57]
Traceback (most recent call last):
  File "/home/zlinbz/miniconda3/envs/bracken/bin/KrakenTools-master/kreport2mpa.py", line 188, in <module>
    main()
  File "/home/zlinbz/miniconda3/envs/bracken/bin/KrakenTools-master/kreport2mpa.py", line 143, in main
    report_vals = process_kraken_report(line)
  File "/home/zlinbz/miniconda3/envs/bracken/bin/KrakenTools-master/kreport2mpa.py", line 80, in process_kraken_report
    taxid = int(l_vals[-3])
NameError: name 'l_vals' is not defined. Did you mean: 'locals'?

Is there anyone met this problem and have solved it?

**Comment by rahel31** [comment]
Same error here : 

....../KrakenTools-master/kreport2mpa.py", line 80, in process_kraken_report
    taxid = int(l_vals[-3])
NameError: global name 'l_vals' is not defined

Did you solve it ? @Sautumn-Lin

**Comment by Sautumn-Lin** [comment]
yes, I just downloaded another "kreporet2.mpa.py", and it finally can be used. When Iuse computer

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sautumn-Lin** [comment]
continue…
when I use computer later, I can send it to you.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rahel31** [comment]
Thank you! Maybe you can put it on google drive and share the downloadable link here? It seems I cannot send an e-mail to you or personal message over github...

**Comment by Sautumn-Lin** [comment]
Using the script directly in the file is ok, if my memory is not wrong.

发件人: rahel31 ***@***.***>
发送时间: 2022年10月28日 13:09
收件人: jenniferlu717/KrakenTools ***@***.***>
抄送: LIN Ziqiu ***@***.***>; Mention ***@***.***>
主题: Re: [jenniferlu717/KrakenTools] error running kreport2mpa.py script, name 'l_vals' is not defined. (Issue #57)


Thank you! Maybe you can put it on google drive and share the downloadable link here? It seems I cannot send an e-mail to you or personal message over github...

―

**Comment by Sautumn-Lin** [comment]
https://github.com/jenniferlu717/KrakenTools/releases/tag/v1.2         
I can not send you the file on this web. You can try downloading it on this link, but I am unsure whether it is the right one.

**Comment by rahel31** [comment]
Ok, thanks :)

**Comment by simonleandergrimm** [comment]
@rahel31 Did this work for you?  I still get the same error. 

@jenniferlu717 did this also happen to others? If so, is there an easy fix on our side?

Traceback (most recent call last):
  File "/[...]/kreport2mpa.py", line 188, in <module>
    main()
  File "/[...]/kreport2mpa.py", line 143, in main
    report_vals = process_kraken_report(line)
  File "/[...]/illumina_pilot/kreport2mpa.py", line 80, in process_kraken_report
    taxid = int(l_vals[-3])
    NameError: name 'l_vals' is not defined. Did you mean: 'locals'?

**Comment by camilagazolla** [comment]
Dear @simonleandergrimm, I used the release v1.1 and it worked! 

You can find it here: https://github.com/jenniferlu717/KrakenTools/releases/tag/v1.1

Any concerns about using this previous version to avoid that error @jenniferlu717? :)

Thank you!!
