### ISSUE TITLE
combining krakenuniq reports 

### ISSUE THREAD

**Issue by Sabrin2020** [jenniferlu717/KrakenTools#83]
Is this scripts could  be working with krakenuniq reports? If yes how to fix it please 

combine_kreports.py -r *-krakenuniq-report.tsv -o COMBINED.KREPORT --display-headers
>>STEP 1: READING REPORTS
        1/301 samples processedTraceback (most recent call last):
  File "/user/asga9989/.conda/envs/krakentools/bin/combine_kreports.py", line 311, in <module>
    main()
  File "/user/asga9989/.conda/envs/krakentools/bin/combine_kreports.py", line 226, in main
    while level_num != (prev_node.level_num + 1):
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'level_num'

 **head _PL17_99indbel-krakenuniq-report.tsv**
```
# KrakenUniq v1.0.3 DATE:2023-08-06T00:57:24Z DB:/gss/work/asga9989/krakenuniq/microbial-nt DB_SIZE:706079654188 WD:/gss/work/asga9989/all_samples_run
# CL:/cm/shared/uniol/software/8.3/KrakenUniq/1.0.3-intel-2019b/bin/krakenuniq --db /gss/work/asga9989/krakenuniq/microbial-nt --threads 20 --fastq-input --gzip-compressed --paired --output 07_TAXONOMY_references_removed/_PL17_99indbel.krakenuniq --report-file 07_TAXONOMY_references_removed/_PL17_99indbel-krakenuniq-report.tsv 01_QC/_PL17_99indbel-FILTERED_R1.fastq.gz 01_QC/_PL17_99indbel-FILTERED_R2.fastq.gz
%       reads   taxReads        kmers   dup     cov     taxID   rank    taxName
43.16   783047  783047  132171775       3.13    NA      0       no rank unclassified
56.84   1031262 3084    504258  49.4    8.57e-06        1       no rank root
56.47   1024531 4231    491054  20.4    8.674e-06       131567  no rank   cellular organisms
54.03   980284  199152  475276  13.8    1.16e-05        2       superkingdom        Bacteria
31.88   578351  139858  424790  6.27    2.301e-05       1224    phylum        Pseudomonadota
12.22   221695  129781  337596  4.34    3.528e-05       1236    class           Gammaproteobacteria
3.011   54630   7       1869    62.1    7.733e-07       91347   order             Enterobacterales
```

**Comment by jenniferlu717** [comment]
The script should work for kuniq reports but I'll check.

**Comment by songkue** [comment]
Hi there, I am also having the same error code when trying to combine my krakenuniq reportfiles. Is there a resolution for this?
Thank you for your help!
